xray_compose_dir: /srv/xray
xray_container_name: xray
xray_image: teddysun/xray

# WS over TLS via Traefik
xray_domain: "{{ lookup('env', 'XRAY_DOMAIN') }}"
xray_ws_path: "/ws"
xray_listen_port: 10000   # internal port inside the xray container
xray_admin_uuid: ""       # will be generated if empty

# Traefik
traefik_network: "traefik-network"
