# Export Xray clients: print to console and save artifacts locally.
- name: Read Xray config.json
  slurp:
    path: "{{ xray_compose_dir }}/config.json"
  register: cfg_raw
  become: true

- name: Parse JSON
  set_fact:
    xray_cfg: "{{ cfg_raw.content | b64decode | from_json }}"

- name: Extract clients array
  set_fact:
    xray_clients: "{{ xray_cfg.inbounds[0].settings.clients | default([]) }}"

- name: Ensure local export dir exists
  file:
    path: "{{ xray_export_dir | default('exports/xray') }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  become: false
  run_once: true

- name: Print header
  debug:
    msg: "email, uuid, vless_url"
  run_once: true

- name: Print each client row
  vars:
    email: "{{ (item.email | default('client')) }}"
    uuid: "{{ item.id }}"
    url: "vless://{{ uuid }}@{{ xray_domain }}:443?encryption=none&type=ws&security=tls&host={{ xray_domain }}&sni={{ xray_domain }}&path={{ xray_ws_path }}#{{ xray_domain }}-ws"
  debug:
    msg: "{{ email }}, {{ uuid }}, {{ url }}"
  loop: "{{ xray_clients }}"

- name: Save URL file locally
  vars:
    email: "{{ (item.email | default('client')) }}"
    uuid: "{{ item.id }}"
    url: "vless://{{ uuid }}@{{ xray_domain }}:443?encryption=none&type=ws&security=tls&host={{ xray_domain }}&sni={{ xray_domain }}&path={{ xray_ws_path }}#{{ xray_domain }}-ws"
  copy:
    dest: "{{ xray_export_dir | default('exports/xray') }}/{{ email }}-{{ uuid }}.url.txt"
    content: "{{ url }}\n"
    mode: "0644"
  loop: "{{ xray_clients }}"
  delegate_to: localhost
  become: false

- name: Save client config.json locally (for Xray-core)
  vars:
    email: "{{ (item.email | default('client')) }}"
    uuid: "{{ item.id }}"
  copy:
    dest: "{{ xray_export_dir | default('exports/xray') }}/{{ email }}-{{ uuid }}.client.json"
    mode: "0644"
    content: |
      {
        "inbounds": [
          {
            "listen": "127.0.0.1",
            "port": 10808,
            "protocol": "socks",
            "settings": { "udp": true }
          },
          {
            "listen": "127.0.0.1",
            "port": 10809,
            "protocol": "http",
            "settings": {}
          }
        ],
        "outbounds": [
          {
            "protocol": "vless",
            "settings": {
              "vnext": [
                {
                  "address": "{{ xray_domain }}",
                  "port": 443,
                  "users": [
                    {
                      "id": "{{ uuid }}",
                      "encryption": "none"
                    }
                  ]
                }
              ]
            },
            "streamSettings": {
              "network": "ws",
              "security": "tls",
              "wsSettings": { "path": "{{ xray_ws_path }}" },
              "tlsSettings": { "serverName": "{{ xray_domain }}" }
            }
          }
        ]
      }
  loop: "{{ xray_clients }}"
  delegate_to: localhost
  become: false

- name: Summary path
  debug:
    msg: "Artifacts saved to {{ xray_export_dir | default('exports/xray') }} (on localhost)."
  run_once: true
