- name: Ensure compose dir exists
  file:
    path: "{{ xray_compose_dir }}"
    state: directory
    mode: "0755"

- name: Generate admin UUID if not provided
  command: uuidgen
  register: gen_uuid
  when: not xray_admin_uuid
  changed_when: false

- name: Set admin UUID fact
  set_fact:
    xray_admin_uuid: "{{ xray_admin_uuid if xray_admin_uuid else gen_uuid.stdout }}"

- name: Render config.json
  template:
    src: config.json.j2
    dest: "{{ xray_compose_dir }}/config.json"
    mode: "0644"
  notify: Restart Xray

- name: Render docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ xray_compose_dir }}/docker-compose.yml"
    mode: "0644"

- name: Up Xray (compose v2)
  community.docker.docker_compose_v2:
    project_src: "{{ xray_compose_dir }}"
    state: present
