# --- cleanup old bits (safe, idempotent) ---
- name: Remove old Traefik container (if exists)
  community.docker.docker_container:
    name: traefik
    state: absent
    force_kill: true
  ignore_errors: true

- name: Remove old Traefik image (if exists)
  community.docker.docker_image:
    name: "traefik"
    state: absent
  ignore_errors: true

- name: Remove legacy 'web' docker network (if exists)
  community.docker.docker_network:
    name: "web"
    state: absent
  ignore_errors: true

# --- network for reverse proxy ---
- name: Ensure external Docker network exists
  community.docker.docker_network:
    name: "{{ traefik_network }}"
    driver: bridge
    state: present

# --- dirs and acme ---
- name: Ensure Traefik directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ traefik_config_dir }}"
    - "{{ traefik_dynamic_dir }}"

- name: Ensure /etc/letsencrypt exists
  become: yes
  file:
    path: "/etc/letsencrypt"
    state: directory
    mode: "0755"

- name: Ensure acme.json exists with proper perms
  become: yes
  copy:
    dest: "{{ traefik_acme_file }}"
    content: "{}"
    mode: "0600"
    owner: root
    group: root
  args:
    force: false

# --- configs ---
- name: Render Traefik static config
  become: yes
  template:
    src: "traefik.yml.j2"
    dest: "{{ traefik_config_dir }}/traefik.yml"
    mode: "0644"
  notify: Restart Traefik

- name: Render Traefik dynamic config (optional)
  become: yes
  when: traefik_use_file_provider | bool
  template:
    src: "dynamic.yml.j2"
    dest: "{{ traefik_dynamic_dir }}/dynamic.yml"
    mode: "0644"
  notify: Restart Traefik

- name: Render Traefik docker-compose.yml
  become: yes
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ traefik_compose_file }}"
    mode: "0644"

# --- run ---
- name: Up Traefik (compose v2)
  become: yes
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_config_dir }}"
    state: present
