- name: Add Xray client
  hosts: app
  gather_facts: no
  become: yes
  vars:
    client_name: "{{ client_name | default('user') }}"
  tasks:
    - name: Include xray role task to add client
      ansible.builtin.include_role:
        name: xray
        tasks_from: add-client.yml
      vars:
        xray_new_client_name: "{{ client_name }}"