- name: Deploy Traefik reverse proxy
  hosts: app
  gather_facts: yes
  roles:
    - role: traefik
      tags: [traefik]

- name: Deploy Xray (behind Traefik)
  hosts: app
  gather_facts: yes
  roles:
    - role: xray
      tags: [xray]
