# 2 spaces; comments in English
- name: Remove old docker packages
  apt:
    name:
      - docker
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes

- name: Ensure keyrings dir exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key (dearmor)
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
  changed_when: false

- name: Detect deb arch for Docker repo
  set_fact:
    docker_deb_arch: >-
      {{ 'amd64' if ansible_architecture in ['x86_64','amd64']
         else 'arm64' if ansible_architecture in ['aarch64','arm64']
         else ansible_architecture }}

- name: Add Docker APT repository (official)
  apt_repository:
    repo: >-
      deb [arch={{ docker_deb_arch }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: yes

- name: Install Docker Engine + compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Verify docker compose v2
  command: docker compose version
  register: compose_v2
  changed_when: false

- name: Show docker compose version
  debug:
    msg: "{{ compose_v2.stdout }}"
